### ISSUE TITLE
Gnome caching

### ISSUE THREAD

**Issue by ghost** [sindresorhus/wallpaper#10]
Hi. I was using your package and suddenly it seemed to have stopped working, it's not really a bug though (Linux).

I am using elementaryOS (Ubuntu) and `gsettings set picture-uri` seems to be caching wallpapers/paths and does not update the wallpaper if a same path is used (I was changing wallpapers every x seconds with the same name in one folder). It doesn't fail, and doesn't give any errors, I'm not too certain how well-known this knowledge is but maybe it is worth mentioning in a readme section? Once you know this it's easy enough to generate random names.

Alternative, something like clearing cache might work? But, this isn't best practice I guess?

**Edit^**: cache is maybe a bit a wrong explanation/terminology. The path image-uri gets set but wallpaper (when same path) does not update until reboot.

Or, maybe something like `wallpaper.set` => "get > set > get > if is the same give warning". Although, it might not be the package it's responsibly.

Thanks for all your work!

**Comment by sindresorhus** [comment]
> clearing cache might work

Do you know how we could do that? I'm not a Linux user.

> Or, maybe something like set => "get > set > get >

How exactly would that solve it?

> Although, it is not really the package it's responsibly.

I disagree. The intention for this module is to be able to set a wallpaper easily, without having to think about whether it gets cached or not.

-

// @fedemp

**Comment by verth** [comment]
> Do you know how we could do that? I'm not a Linux user.

Not by heart, I've seen it somewhere but didn't test it (renaming did the trick). I'll see if I can find/test it! (Or maybe someone will be faster, *something something ~/.cache/wallpaper*)

> Or, maybe something like set => "get > set > get >

Would not really solve the problem but it can give some insights to people running into this problem. Same as readme.

> Although, it is not really the package it's responsibly.

I get your point, true, don't disagree! But it's the other package that is "failing" and I didn't want to sound rude by passing responsibility to you.

**Comment by fa7ad** [comment]
I feel like this is out of scope of this project as the "bug" is in gsettings and gnome rather than this tool.

**Comment by sindresorhus** [comment]
Can anyone open an issue ticket on gsettings or Gnome and comment the link here so I can close this issue?

**Comment by verth** [comment]
[Launchpad](https://bugs.launchpad.net/switchboard-plug-pantheon-shell/+bug/1534274) has an open ticket for this issue, although it has not yet been verified. Good for me to close this.

**Comment by sindresorhus** [comment]
Closing as the linked issue was closed as "Won't fix" and I don't intend on working around it.
