### ISSUE TITLE
Wallpaper does not set in OS X if in a full-screen app

### ISSUE THREAD

**Issue by tma02** [sindresorhus/wallpaper#11]
If you attempt to set the wallpaper in OS X while you're in a full-screen application the wallpaper does not get changed.

**Comment by sindresorhus** [comment]
It sets the wallpaper on the main screen: https://github.com/sindresorhus/osx-wallpaper/blob/f0f86a2dd6a8ea31257abd6075d434fe2088f087/wallpaper.m#L15 I guess the main screen is the fullscreen "screen" when in fullscreen. Not really sure how to detect the non-fullscreen main screen. Help welcome :)

**Comment by tma02** [comment]
What about using the ```screens``` object https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSScreen_Class/#//apple_ref/occ/clm/NSScreen/screens
to set the wallpaper for all screens?

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/osx-wallpaper/commit/acb681606ef40692df9f54a8309e4a7bde0dd240.
