### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by demiurgosoft** [sindresorhus/wallpaper#13]
Running your example:
```javascript
const wallpaper = require('wallpaper');

wallpaper.set('unicorn.jpg').then(() => {
    console.log('done');
});

wallpaper.get().then(imagePath => {
    console.log(imagePath);
    //=> '/Users/sindresorhus/unicorn.jpg'
});
```

On Linux Ubuntu throws an error on `/lib/linux.js`:
```
return cp.execFile(app.cmd, app.get).then(stdout => 

TypeError: Cannot read property 'cmd' of undefined
```

Seems to be due to using async functions (get and set) at the same time (same problem with different error if using get before set

The problem solves simply using the second command inside the callback:

```javascript
const wallpaper = require('wallpaper');

wallpaper.set('unicorn.jpg').then(() => {
    console.log('done');
	wallpaper.get().then(imagePath => {
	    console.log(imagePath);
	    //=> '/Users/sindresorhus/unicorn.jpg'
	});
});
```

I'm not sure if the problem is just in linux, and if its an error in the example code or in the linux library.

**Comment by kevva** [comment]
The example is just meant to show how you use the methods individually. It assumes that people know about async.

**Comment by demiurgosoft** [comment]
Wouldn't be better to use 2 different examples? just for better clarity.

**Comment by kevva** [comment]
Both @sindresorhus, me and tons of authors are doing examples like this in many modules. It's somewhat expected that users have some knowledge about how async works :). I.e, doing two async operations at the same time that depends on each other will mostly break.

**Comment by SamVerschueren** [comment]
Agree with @kevva , no need to change it.

**Comment by kevva** [comment]
Also, what if you expose more than two methods? To separate all those into their own examples would only clutter the documentation.

**Comment by demiurgosoft** [comment]
If making more examples is a problem, simply by splitting the example code would show to a new user it is not meant to work with copy-paste:

```javascript
wallpaper.set('unicorn.jpg').then(() => {
    console.log('done');
});
```
```javascript
wallpaper.get().then(imagePath => {
    console.log(imagePath);
    //=> '/Users/sindresorhus/unicorn.jpg'
});
```
It is not a big deal, but it may make the example a little bit more clear to people who just want a first _"Hello World"_ to try

**Comment by kevva** [comment]
That's what I meant by cluttering the docs.

**Comment by demiurgosoft** [comment]
well... it's one white line, but ok.It was just an idea
