### ISSUE TITLE
Source code of win-wallpaper.exe

### ISSUE THREAD

**Issue by Rafi993** [sindresorhus/wallpaper#14]
It would be nice if you would post the source code of  **win-wallpaper.exe** .

**Comment by sindresorhus** [comment]
It's linked to from the readme.

https://github.com/sindresorhus/win-wallpaper

**Comment by Rafi993** [comment]
sorry for raising this issue

**Comment by sindresorhus** [comment]
No worries, I've made it clearer: https://github.com/sindresorhus/wallpaper/commit/f5d7307e44e8f9125ea3b5fc5113742a967a433a
