### ISSUE TITLE
 Expected empty line after require statement not followed by another require error in travis cli

### ISSUE THREAD

**Issue by Rafi993** [sindresorhus/wallpaper#16]
When Pull request is created the travis cli raises  **Expected empty line after require statement not followed by another require** . Inspite of giving empty line after each require as reported by you [here](https://github.com/benmosher/eslint-plugin-import/issues/318)  the issue exist

**Comment by SamVerschueren** [comment]
See https://github.com/sindresorhus/wallpaper/pull/15#discussion_r69551142
