### ISSUE TITLE
Crashes on GNOME

### ISSUE THREAD

**Issue by fa7ad** [sindresorhus/wallpaper#18]
I get this error when I run

``` js
wallpaper.get().then(console.log)
```

Error: 

``` log
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: gsettings get org.cinnamon.desktop.background picture-uri
No such schema 'org.cinnamon.desktop.background'
```

First I thought it was a bug on my fork, so I tried pulling from your repo, and then I tried installing the package from npm again. Same problem, my guess is that the command for _Cinnamon_ somehow replaces the command for _GNOME_ (probably because they both use `gsettings`).

**Comment by fa7ad** [comment]
UPDATE: just as I expected, moving the block for cinnamon above the command for GNOME "fixes" it.

**Comment by Sohail05** [comment]
@fa7ad 
As you may have already figured out, it iterates over the list and picks the last valid cmd.
Moving the block would break it for "cinnamon" environment.

Your "proposed" feature is a valid workaround but wouldn't make it an out of the box solution (environment agnostic).

Just a few ideas:
 -  `gsettings list-schemas | grep desktop.background` to list all possibilities.
 -  `gsettings writable org.(gnome|cinnamon).desktop.background picture-uri` with an expected stdout of true.

**Comment by fa7ad** [comment]
@sindresorhus this looks promising, but I don't think `execFile` supports piping output to a different command. Can you think of a way to handle this?

**Comment by sindresorhus** [comment]
I don't see why you need piping at all. Execute `gsettings list-schemas` and use JS to get the `desktop.background` from the result.

**Comment by sindresorhus** [comment]
I don't see why you need piping at all. Execute `gsettings list-schemas` and use JS to get the `desktop.background` from the result.

**Comment by fa7ad** [comment]
@sindresorhus so, this has to be executed during the app detection process correct?

**Comment by sindresorhus** [comment]
@fa7ad Yes

**Comment by fa7ad** [comment]
PR #17
