### ISSUE TITLE
Feature Proposal: Control over get method

### ISSUE THREAD

**Issue by fa7ad** [sindresorhus/wallpaper#19]
What do you think about optional "environment" names?
One way to make sure the correct flags are used when the command is same but he environment is different.

Example:

``` js
wallpaper.get().then(console.log) // behaves normally (current behaviour)

wallpaper.get('cinnamon').then(console.log) // tries only the command for cinnamon and nothing else
```

This could be also be useful for people that use multiple Desktop Environments / Tools. Plus, it would be an "easy" way to fix #18 **AND** avoid future problems like this

**Comment by sindresorhus** [comment]
Sounds like a leaky abstraction. I don't think this is how we should fix it.

> it would be an "easy" way to fix 

I prefer proper fixes, not easy ones.

**Comment by fa7ad** [comment]
yeah, figured as much. @Sohail05's suggestions seem better.
Although, I think this could be useful even if its not relevant to that issue (i.e. Multiple environments)

> I use feh, nitrogen AND gnome3. So wallpaper has 1/3 chance of choosing the right program by default.

**Comment by sindresorhus** [comment]
Sorry, I'm not a Linux user. Why would you use multiple environments?

**Comment by fa7ad** [comment]
@sindresorhus many reasons, including but not limited to *lower resource usage* for some work, *multiple users* et al.

**Comment by sindresorhus** [comment]
And there's no standard Linux way of getting the active environment?

**Comment by fa7ad** [comment]
@sindresorhus none that's guaranteed to work, no. 
Some window managers/desktop environments set, **$DESKTOP_SESSION**, some don't. GDM sets $**GDMSESSION**, mdm doesn't.

but **$DESKTOP_SESSION** is an accepted convention by most WMs and DEs but, the problem stays the same, if you're under i3 ~~for example~~, you could be using any number of apps to change the desktop background, including `feh` and `nitrogen`

**Comment by Quacky2200** [comment]
This is an old issue but after looking at the issue referenced above (issue #27) I had a couple of ideas. They're not the best of ideas as it may not always be practical but...

- Could you detect the environment by looking at the running processes using child_process (e.g. gdm + gnome_shell is most always going to be gnome, kdm and KDE/plasma to KDE, cinnamon, etc)?

- Could you combine the end results with the other methods to create a 'score' and use the one with the most points to be the most likely

- Could you present a read-only list that people could use to see why the library tried to pick the environment (perhaps for debugging purposes)

- Could you present a method to allow users to select the method they choose from the above implementation

    **The 'score' list could also remove any environments that do not give a score higher than zero**

    Examples:
  - wallpaper.set('wallpaper.jpg', wallpapers.getEnvironmentList(2) // Set the wallpaper using the second likely environment by parameter
  - wallpaper.set('wallpaper.jpg', wallpapers.getEnvironmentList()[2] // Set the wallpaper using the second likely environment by array
  - wallpaper.setEnvironmentByLikelihood(2) // Method that sets the 2nd most likely environment
