### ISSUE TITLE
Windows group policies

### ISSUE THREAD

**Issue by manikantag** [sindresorhus/wallpaper#2]
Hi, will this able to change the wallpaper even admin disabled the changing wallpapers through Windows group policies? I m looking for that since sometime. 

My idea is to show some blank canvas beneath all the icons on the desktop and apply image to that canvas. But I m not sure how to do that. I only know Java & JavaScript :)

Thanks.

**Comment by sindresorhus** [comment]
No idea, I haven't tested it with that, and would have no idea of how to do so. Let me know if you test though ;)

**Comment by Rafi993** [comment]
I tried setting up group policy and tested it. It seems to work perfect.

**Comment by sindresorhus** [comment]
@Rafi993 Cool. Thanks for testing.
