### ISSUE TITLE
set wallpaper doesn't work

### ISSUE THREAD

**Issue by SevenOutman** [sindresorhus/wallpaper#23]
My script looks like this:

```babel
wallpaper.set(fullImagePath).then(() => {
  console.log('Set as wallpaper')
  wallpaper.get().then(imagePath => {
       console.log(`Current wallpaper: ${imagePath}`)
  })
})
```
which is run by `crontab` on Ubuntu 16.04 (with GNOME).
The wallpaper doesn't change, and the logged `imagePath` does not equal `fullImagePath`.
The output was like: 

    Image already downloaded at: /home/doma/scripts/bing-wallpaper-script/downloads/20170605.jpg
    Set as wallpaper
    Current wallpaper: /usr/share/backgrounds/warty-final-ubuntu.png

However when I run this script manually (not invoke by crontab), it works fine.

**Comment by fa7ad** [comment]
Could it be a problem with the user being used to execute the commands from crontab?

**Comment by SevenOutman** [comment]
@fa7ad Not really. I run crontab as the same user with that when I run my script manually. By the way, if `set` method fails on user permission, I think its Promise should have been rejected.

**Comment by fa7ad** [comment]
FWIW, can you try running the script through a nodejs script? 

```js
setInterval(() => {
  wallpaper.set(...)
}, 60000)
```

and keeping that running (like a daemon)

**Comment by SevenOutman** [comment]
@fa7ad Thanks, your approach may work. However, it's not actually my final goal to change wallpaper at an interval. I was trying to run my script upon system wakeup (Ubuntu has hooks for that), but it didn't work. So I tried running my script with crontab, but it didn't work as well. I guess these 2 scenarios have a same cause, so I only mentioned the crontab scenario in this issue for easier understanding.

**Comment by fa7ad** [comment]
@SevenOutman If your goal is to run at startup, try creating a .desktop file at `~/.config/autostrart` or using a systemd service (just set the user and group options)

**Comment by SevenOutman** [comment]
@fa7ad Thanks for your advice. But I want to run my script at wakeup, not startup.

**Comment by fa7ad** [comment]
@SevenOutman sorry, missed that. well, good luck
