### ISSUE TITLE
I am having an issue when i set the wallpaper from electron app

### ISSUE THREAD

**Issue by ravisojitra** [sindresorhus/wallpaper#26]
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: D:\ionic\demos\electron\electron-tutorial\node_mo
dules\wallpaper\lib\win-wallpaper.exe D:\ionic\demos\electron\electron-tutorial\google.png
Failed to set the desktop wallpaper
(node:2432) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proces
s with a non-zero exit code.

I have the google.png image in my path but it's still not setting the wallpaper but generating an error.

**Comment by fa7ad** [comment]
Just curious, did you try to set the wallpaper from the electron process or the rendered page?

**Comment by ravisojitra** [comment]
Yes, I tried to set it from the electron's main process at the time of creating window function.

**Comment by huaibaomengxiang** [comment]
I have same problem,have you find a way to solve it?

**Comment by ravisojitra** [comment]
No, I couldn't find any solution.

**Comment by ctexxx** [comment]
Probably the process needs administrator privileges?
Furthermore I think this belongs to this repository https://github.com/sindresorhus/win-wallpaper
