### ISSUE TITLE
Failed to set the desktop wallpaper

### ISSUE THREAD

**Issue by huaibaomengxiang** [sindresorhus/wallpaper#29]
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: E:\new Object\node\small\getpic\node_modules\_wallpaper@2.5.0@wallpaper\lib\win-wallpaper.exe E:\new Object\node\small\getpic\RoyalAlcazars_EN-AU13378849776.png

this is the error message. i have the picture

**Comment by AJLoveChina** [comment]
windows fail to set image , but no error info

**Comment by huaibaomengxiang** [comment]
yes,it is very strange

**Comment by Rafi993** [comment]
@huaibaomengxiang  are you using windows 10 ?

**Comment by sindresorhus** [comment]
I don't intend on supporting Window 7.
