### ISSUE TITLE
Error setting images as wallpaper in Windows

### ISSUE THREAD

**Issue by geopelia** [sindresorhus/wallpaper#3]
Under Windows 7 I have errors when configuring images as wallpaper. Mostly with png files but also with some jpg. 
With a png image.
Trace:
Error: Command failed: ./wallpaper.exe C:\Users\myuser\Pictures\walls\zohk0p38npend5mulxkm.png
Failed to set the desktop wallpaper
    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

With a jpg image.
Error: Command failed: ./wallpaper.exe C:\Users\myuser\Pictures\walls\05-11-2010.jpg
Failed to set the desktop wallpaper
    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by sindresorhus** [comment]
Can you share those files?

**Comment by geopelia** [comment]
This is the script i use
(https://gist.github.com/a855f0dd6116fbf790d5.git)
These are the images. 
![05-11-2010](https://cloud.githubusercontent.com/assets/776124/7253629/cc54c0ac-e807-11e4-8092-bb76f599aaa8.jpg)
![zohk0p38npend5mulxkm](https://cloud.githubusercontent.com/assets/776124/7253636/d7bc0388-e807-11e4-87fa-0202cc8f7239.png)

**Comment by Rafi993** [comment]
@geopelia    I executed the following code 

```
var fs = require('fs'),
wallpaper = require('wallpaper'),
path = require('path');

var p = "./";
fs.readdir(p, function (err, files) {
    if (err) {
        throw err;
    }
    var images = files.map(function (file) {
        return path.join(p, file);
    }).filter(function (file) {
        var extList = [".jpg", ".png"];
        return (fs.statSync(file).isFile() && extList.indexOf(path.extname(file).toLowerCase()) != -1);      
    })
    setWallpaper(images);

});
function setWallpaper(images) {
	var image = images[Math.floor(Math.random() * images.length)];
	console.log(image);

    wallpaper.set(image, function (err) {
        if (err) {
            throw err;
        }
        console.log('done');
    });
}

setWallpaper("../testdata")
```
But I was unable to reproduce the error. But the wallpaper did not change. When I did getwallpaper method it returned the name passed in set.

**Comment by fa7ad** [comment]
Can't reproduce, I tried the same image on Windows 7 Ultimate (x64).
