### ISSUE TITLE
Uncaught (in promise) Error: spawn /macos-wallpaper ENOENT

### ISSUE THREAD

**Issue by steven-Zzz** [sindresorhus/wallpaper#30]
i use wallpaper in mac, `wallpaper` don't works, find  the error message.

**Comment by fa7ad** [comment]
just curious, what are you calling the function from?

**Comment by steven-Zzz** [comment]
@fa7ad  
```
import wallpaper from 'wallpaper';
...
...
wallpaper.get();
```
just this.

**Comment by fa7ad** [comment]
sorry for not being clear, i meant to ask what environment is it executing in (e.g. Node, Electron, Browser etc)

**Comment by steven-Zzz** [comment]
sure, work in Electron.

**Comment by fa7ad** [comment]
that could be why, it can't properly resolve the location of the macos binary inside electron (at least from the renderer process), you might have better luck putting the code in the electron main process and communicate the output to frontend using ipc

**Comment by steven-Zzz** [comment]
sorry for reply is so late,  i have just touched this thing, not very understanding.

**Comment by sindresorhus** [comment]
You probably have ASAR enabled, and it doesn't support `spawn`. Try https://github.com/epsitec-sa/hazardous
