### ISSUE TITLE
[Mac os] Set wallpaper on all spaces 

### ISSUE THREAD

**Issue by lucdandrel** [sindresorhus/wallpaper#31]
Hello, 
Thank you very much for this package! It helps me a lot for a project.
But i have a little suggestion for improvement. 
Is it possible to put an image as wallpaper on all spaces with mac os?

Thank you !

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/macos-wallpaper/issues/4

**Comment by lucdandrel** [comment]
Ok thanks, I work on it ;) ! And if I succeed, I will do a pull request.
