### ISSUE TITLE
Set lock screen wallpaper on Windows

### ISSUE THREAD

**Issue by xeoneux** [sindresorhus/wallpaper#33]
Is this currently supported?

**Comment by sindresorhus** [comment]
No

**Comment by fa7ad** [comment]
@Ahijah was rejected last time I brought it up (for linux)

**Comment by sindresorhus** [comment]
I don't know any programmatic way to change the lockscreen wallpaper, but if anyone does, PR welcome on https://github.com/sindresorhus/win-wallpaper
