### ISSUE TITLE
cp.exec is not a function

### ISSUE THREAD

**Issue by Sijoma** [sindresorhus/wallpaper#35]
I get the following error when launching the wallpaper.get() function to retrieve the path of the current background image inside my components.  It works from the electron process. Is it problematic that the linux.js is used even though I am on windows 10 at the moment?

![grafik](https://user-images.githubusercontent.com/8970764/41432015-09de8c26-7015-11e8-8294-3478a3819170.png)

**Comment by sindresorhus** [comment]
You cannot use this module in the Electron renderer process. Call it with `remote.require` instead. Also, make sure it's not run through Webpack. This applies in general to any Node.js-only module.
