### ISSUE TITLE
Wallpaper not updated when fullscreen app is focused

### ISSUE THREAD

**Issue by Rawnly** [sindresorhus/wallpaper#48]
#### Generic infos

- **Platform**: MacOS Mojave
- **Node**: v8.12.0

#### Issue
The wallpaper is not updated when user focus a fullscreen application.

From: [#36](https://github.com/splash-cli/splash-cli/issues/36)

**Comment by sindresorhus** [comment]
When an app is fullscreen, it's technically in a separate "space". Settings the wallpaper for multiple spaces is not possible, see: https://github.com/sindresorhus/macos-wallpaper/issues/4

Closing as this will need to be fixed by Apple.
