### ISSUE TITLE
Error: spawn /macos-wallpaper ENOENT

### ISSUE THREAD

**Issue by soroushchehresa** [sindresorhus/wallpaper#49]
Hi,
When I use every method of this library like `wallpaper.get()` I get this error:
```
Uncaught (in promise) Error: spawn /macos-wallpaper ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229)
    at onErrorNT (internal/child_process.js:406)
    at process._tickCallback (internal/process/next_tick.js:63)
```
I checked out #30 but it didn't work for me. 

**note**:
When I run `console.log(process.platform)` from all over the application return `darwin`.

os: macOS High Sierra 10.13.4
node: 10.12.0
npm: 6.4.1
electron v3.0.5
wallpaper: ^4.1.0
wallpaper-cli: ^2.0.0

**Comment by sindresorhus** [comment]
This is an Electron issue: https://github.com/electron/electron/issues/9459
