### ISSUE TITLE
Use website as wallpaper?

### ISSUE THREAD

**Issue by ohld** [sindresorhus/wallpaper#59]
Hi there!

Is there a solution to set a website as a wallpaper os mac os? 

I've seen some solutions on ProductHunt but none of them still work or are maintained.

In my company, we have a dashboard with all our business metrics - it is hosted in the private VPN network. We want to see all of these numbers on our wallpaper on our laptops. Is there a solution of that?

**Comment by TiagoDanin** [comment]
Get the image via [`download`](https://github.com/kevva/download#readme) or [`capture-website`](https://github.com/sindresorhus/capture-website) and user the `wallpaper`

Example: 
```js
// ...
await captureWebsite.file('https://sindresorhus.com', 'screenshot.png')
await wallpaper.set('screenshot.png')
// ...
```

**Comment by ohld** [comment]
Thanks for your answer! In my case, the website has a lot of graphs that are displayed-as-a-slideshow. Is there a solution just to embed the website into the wallpaper?

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/wallpaper#faq
