### ISSUE TITLE
Cross Fade to another image - possible?

### ISSUE THREAD

**Issue by NineNineNineIonoSpheres** [sindresorhus/wallpaper#61]
When invoking, for example, 

`wallpaper.set('unicorn.jpg');`

is it possible to make it so the wallpaper crossfade to another image, not just instantly change?

**Comment by sindresorhus** [comment]
You didn't mention what OS you need it for. On macOS, it's possible to do it by placing a window at the desktop level filled with the desktop wallpaper, replace the wallpaper, and fade out the window. This creates the cross-fade effect. For other OSes, I have no idea. This is outside the scope of this package regardless.
