### ISSUE TITLE
Error when importing wallpaper

### ISSUE THREAD

**Issue by lihaobhsfer** [sindresorhus/wallpaper#65]
I am getting an error when importing wallpaper to my project:

`TypeError: The "original" argument must be of type Function`

It seems the `promisify` function in the `util` library it is referencing. I've tried only using the macos files and importing locally using other promisify packages, but they resulted in other errors.

Is it because of the version of the `util` library? According to where the error pointed to me, I'm using 0.11.1

OS: macOS 10.15.3
Node: 10.16.0
npm 6.13.1

Anyone got a solution? Thanks!

**Comment by sindresorhus** [comment]
I don't know what you're trying to do, but it sounds like you're trying to build this package with Webpack or something and it's replacing the Node.js APIs with shims. Support questions like this is better asked elsewhere as it's not really specific to this package.

I'm happy to look into this further if you submit a failing test to prove that it's actually something wrong with `wallpaper`.
