### ISSUE TITLE
Feature Proposal: Video Support or WebView Support

### ISSUE THREAD

**Issue by LeoCreer** [sindresorhus/wallpaper#67]
I it is all possible for video support.

`await wallpaper.set('unicorn.mp4');`

or 

// this could be internal or external. // ** 'http://unicorn.com'**

`await wallpaper.setURL('local/unicorn.html');`

// This will give us the ability to create cool canvas backgrounds. 
See examples.
https://codepen.io/alexzaworski/pen/mEkvAG
https://codepen.io/jasperlachance/pen/QNMwBg

**Comment by sindresorhus** [comment]
This is answered in the FAQ in the readme.
