### ISSUE TITLE
KDE/Plasma not working.

### ISSUE THREAD

**Issue by VictorioBerra** [sindresorhus/wallpaper#70]
Tested with Arch and Kubuntu, no errors. When I run the command from desktop-managers/qdbus.js it works:

`qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops(); for (var i = 0; i < allDesktops.length; i++) { var desktop = allDesktops[i]; desktop.wallpaperPlugin = "org.kde.image"; desktop.currentConfigGroup = ["Wallpaper", "org.kde.image", "General"]; desktop.writeConfig("Image", "file://home/tory/Pictures/image.png"); }'`

But for some reason it does not work when this module calls it.

**Comment by sindresorhus** [comment]
Note that the Linux implementation is without a maintainer. I don't use Linux. But PRs are welcome.
