### ISSUE TITLE
Cannot be opened ecause the developer cannot be verified

### ISSUE THREAD

**Issue by gergof** [sindresorhus/wallpaper#77]
I use this app in an electron application which is signed and notarized correctly. After installing this library I get the error mentioned in the title. How could I resolve this?

**Comment by sindresorhus** [comment]
You need to notarize bundled binaries too. The provided binary here cannot be notarized as binaries cannot be directly notarized. They need to be in a container like an app bundle or ZIP file.

**Comment by gergof** [comment]
Thanks for the quick reply! Can you give me any indication on how to do that?

**Comment by gergof** [comment]
I've created a fork of this repo which uses node addons instead of bundled executables which resolves my problem. I also migrated it to typescript.

It can only get the wallpapers for now, but I will add the set functionality later.

https://github.com/gergof/node-wallpaper
