### ISSUE TITLE
Promisify Linux version

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/wallpaper#8]
This file: https://github.com/sindresorhus/wallpaper/blob/4d1dbc3e582328cb1e0da65b94ebe6191f73bbe5/lib/linux.js

I just wrapped it in `pify` for now: https://github.com/sindresorhus/wallpaper/blob/a1d20f1703135a1a8f3e302eae234ce4dc6bb002/index.js#L8

-

// @SamVerschueren @kevva @arthurvr in case any of you are interested. No worries if not. If you're doing it, comment so we don't end up with duplicated work.

**Comment by SamVerschueren** [comment]
On it!

**Comment by SamVerschueren** [comment]
@sindresorhus Can you explain more in detail what this does?

```js
	availableApps.forEach(app => {
		if (!app.set) {
			return;
		}

		const params = JSON.parse(JSON.stringify(app.set));
		params[params.length - 1] = params[params.length - 1].replace('%s', imagePath);

		childProcess.execFile(app.cmd, params, err => cb(err));
	});
```

It calls the callback for every `availableApps` entry, is this correct?

**Comment by sindresorhus** [comment]
It goes through all the found "apps" and executes its [`set`](https://github.com/sindresorhus/wallpaper/blob/4d1dbc3e582328cb1e0da65b94ebe6191f73bbe5/lib/linux.js#L8-L11) command. In hinsight this is very wrong, and it should only execute and callback the first found that has a `set` method, not all of them.

**Comment by SamVerschueren** [comment]
Thanks for the clarification, will fix it.
