### ISSUE TITLE
When I import from 'wallpaper'

### ISSUE THREAD

**Issue by SitoNumbis** [sindresorhus/wallpaper#80]
Being on Windows and Linux: Debian Bulleye
./node_modules/wallpaper/source/linux/util.js
Module not found: Can't resolve 'node:child_process' in '[project-dir]\node_modules\wallpaper\source\linux'

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
