### ISSUE TITLE
5.x version with native Apple Silicon support

### ISSUE THREAD

**Issue by sunjw** [sindresorhus/wallpaper#85]
Native Apple Silicon support is added after 6.x in this commit: https://github.com/sindresorhus/wallpaper/commit/bbcf7ce2d3390a7e672d5e56ce6663b273532f1f

But 6.x also using ESM which Electron not support well. Could the Apple Silicon support executable be merged back to 5.x, to make a newer 5.x version, with native arm64 executable and without ESM.

**Comment by sindresorhus** [comment]
I have no plans to do that. There are ways to use ESM with Electron if you check the Electron issue.
