### ISSUE TITLE
Incompatible with cjs.

### ISSUE THREAD

**Issue by 40oleg** [sindresorhus/wallpaper#88]
The problem is that I have a project which use commonjs modules system, but library only works with esm.

Screenshot of error when I tried to run library on cjs project.
![image](https://user-images.githubusercontent.com/60510512/220861783-f4c32bcd-be40-4bcf-8933-38936f2eaa42.png)

Thank you for attention!

**Comment by 40oleg** [comment]
I really like your library and I would like to solve this problem if someone can give me a little hint on how it can be solved.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
