### ISSUE TITLE
"fileURLToPath" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by nolongerhesitate** [sindresorhus/wallpaper#90]
`"fileURLToPath" is not exported by "__vite-browser-external", imported by "node_modules/.store/wallpaper@6.1.1/node_modules/wallpaper/source/macos.js".
file: /Users/sungbang/Projects/HelloWorldProjects/Electron/rwallpapers-vite/node_modules/.store/wallpaper@6.1.1/node_modules/wallpaper/source/macos.js:4:8`
![image](https://user-images.githubusercontent.com/9473998/236493721-3a5892fd-bf93-4103-a093-4fb58e915cd5.png)

This error was reported when I ran the script "vite build". Could you help me? What should I do?

Versions :
wallpaper : 6.1.1
vue: 3.2.47

**Comment by sindresorhus** [comment]
This is a problem with your Vite config, not this package. I suggest asking in the Vite support channels.

**Comment by nolongerhesitate** [comment]
ok，thanks for you help。
